### PR TITLE
remove --no-ri --no-rdoc

### PR DESCRIPTION
**Pull request by remotedevops**
Fix for rubygems 3.0.3.

### CODE REVIEW

**Comment by ess** [comment]
@remotedevops hey duder. Please rebase from deploy and push again. I've just pushed a gem version specification to it that should fix the CI issues.

**Comment by remotedevops** [comment]
@ess deploy or develop?  I rebased from develop and pushed again.

**Comment by ess** [comment]
@remotedevops Indeed, I meant develop. Thanks!

**Comment by ess** [comment]
LGTM

**Comment by ess** [comment]
Resolves #185

**Pull request merged**
